// Downloads the official names of game terms used on the site, in all of the game's languages, from the
// Genshin Impact Fandom wiki, and saves them to messages/glossary.json for translators.
//
// Usage: npm run glossary
//
// Each term's wiki page has an {{Other Languages}} template listing its name in every language the game supports.
// Some terms have no page of their own; for those, a page whose name contains the term is used, with a note.
import { writeFile } from "node:fs/promises";

const Api = "https://genshin-impact.fandom.com/api.php";
const Output = new URL("../messages/glossary.json", import.meta.url);

/** Terms used on the site, and the wiki page their translations are taken from. */
const terms = [
  { key: "original_resin", page: "Original Resin" },
  { key: "realm_currency", page: "Realm Currency" },
  { key: "serenitea_pot", page: "Serenitea Pot" },
  {
    key: "adeptal_energy",
    page: "High Adeptal Energy Readings Ahead",
    note: "No page of its own. This achievement's name contains the term.",
  },
  {
    key: "trust_rank",
    page: "Trust",
    note: "No page of its own. This is the name of Trust, the experience that raises the Trust Rank.",
  },
  { key: "teyvat", page: "Teyvat" },
  { key: "paimon", page: "Paimon" },
  { key: "klee", page: "Klee" },
  { key: "diluc", page: "Diluc" },
  { key: "tartaglia", page: "Tartaglia" },
  { key: "zhongli", page: "Zhongli" },
  { key: "xiao", page: "Xiao" },
  { key: "hu_tao", page: "Hu Tao" },
  { key: "kazuha", page: "Kaedehara Kazuha" },
  { key: "ayaka", page: "Kamisato Ayaka" },
];

/** Wiki language codes and the site's language codes (see src/lib/languages.ts). */
const languages = {
  en: "en-US",
  zhs: "zh-Hans",
  zht: "zh-Hant",
  ja: "ja",
  ko: "ko",
  es: "es",
  fr: "fr",
  ru: "ru",
  th: "th",
  vi: "vi",
  de: "de",
  id: "id",
  pt: "pt",
  tr: "tr",
  it: "it",
};

async function getWikitext(page) {
  const url = new URL(Api);
  url.search = new URLSearchParams({
    action: "parse",
    page,
    prop: "wikitext",
    format: "json",
    formatversion: "2",
    redirects: "1",
  }).toString();

  const response = await fetch(url, { headers: { "user-agent": "genshin-schedule glossary script" } });
  const data = await response.json();

  if (data.error) {
    throw new Error(`${page}: ${data.error.info}`);
  }

  return data.parse.wikitext;
}

/** Returns the parameters of the first {{Other Languages}} template, e.g. { en: "Original Resin", ja: "天然樹脂" }. */
function parseOtherLanguages(wikitext) {
  const start = wikitext.indexOf("{{Other Languages");

  if (start < 0) {
    return;
  }

  // find the end of the template, which may contain other templates
  let depth = 0;
  let end = start;

  do {
    if (wikitext.startsWith("{{", end)) {
      depth++;
      end += 2;
    } else if (wikitext.startsWith("}}", end)) {
      depth--;
      end += 2;
    } else {
      end++;
    }
  } while (depth > 0 && end < wikitext.length);

  const params = {};

  for (const line of wikitext.slice(start, end).split("\n")) {
    const match = line.match(/^\|\s*([\w]+)\s*=(.*)$/);

    if (match) {
      params[match[1]] = match[2].trim();
    }
  }

  return params;
}

/** Removes wiki markup from a name, e.g. ruby text, tooltips and references. */
function clean(value) {
  return (
    value
      .replace(/<ref[^>]*>.*?<\/ref>|<ref[^>]*\/>/g, "")
      // {{Rubi|塵|じん|歌|か}} shows 塵歌 with readings above it
      .replace(/\{\{Rubi\|([^}]*)\}\}/g, (_, args) =>
        args
          .split("|")
          .filter((_, i) => i % 2 === 0)
          .join(""),
      )
      // {{tt|text|tooltip}}
      .replace(/\{\{tt\|([^|}]*)(\|[^}]*)?\}\}/g, "$1")
      .replace(/\{\{[^}]*\}\}/g, "")
      .replace(/\[\[(?:[^|\]]*\|)?([^\]]*)\]\]/g, "$1")
      .replace(/\/\//g, "")
      .replace(/'''?/g, "")
      .trim()
  );
}

const glossary = {
  $comment:
    "Official names of game terms in the game's languages, from the Genshin Impact Fandom wiki. Generated by `npm run glossary`; don't edit by hand. Translations should use these names.",
  terms: {},
};

for (const { key, page, note } of terms) {
  const params = parseOtherLanguages(await getWikitext(page));

  if (!params) {
    throw new Error(`${page}: no {{Other Languages}} template`);
  }

  // some pages list several names in numbered rows (1_en, 2_en, ...); the first row is the page's subject
  const prefix = "en" in params ? "" : "1_";
  const names = {};

  for (const [wiki, language] of Object.entries(languages)) {
    const value = params[prefix + wiki];

    if (value) {
      names[language] = clean(value);
    }
  }

  glossary.terms[key] = {
    source: `https://genshin-impact.fandom.com/wiki/${encodeURIComponent(page.replaceAll(" ", "_"))}`,
    ...(note && { note }),
    names,
  };

  console.log(`${key}: ${Object.keys(names).length} languages`);
}

await writeFile(Output, JSON.stringify(glossary, null, 2) + "\n");
console.log(`Wrote ${Output.pathname}`);
